webtalk_init -webtalk_dir D:\\UTK_Project\\Daimler_Project\\XCP\\XCP.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2020-04-19 10:12:06" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "v5h1sf7m4bebejvvjscfvfh3db" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.2_26" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "26" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-7440HQ CPU @ 2.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2808 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.992 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1587047275634" -context "sdk\\\\application/1587047275634"
webtalk_add_data -client sdk -key hwid -value "1586096762409" -context "sdk\\\\application/1587047275634"
webtalk_add_data -client sdk -key bspid -value "1586450648187" -context "sdk\\\\application/1587047275634"
webtalk_add_data -client sdk -key newbsp -value "false" -context "sdk\\\\application/1587047275634"
webtalk_add_data -client sdk -key os -value "freertos10_xilinx" -context "sdk\\\\application/1587047275634"
webtalk_add_data -client sdk -key apptemplate -value "freertos_lwip_udp_perf_server" -context "sdk\\\\application/1587047275634"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1587047275634"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1587047275634"
webtalk_add_data -client sdk -key Procused -value "ps7_cortexa9" -context "sdk\\\\application/1587047275634"
webtalk_add_data -client sdk -key uid -value "1587051422935" -context "sdk\\\\application/1587051422935"
webtalk_add_data -client sdk -key hwid -value "1586096762409" -context "sdk\\\\application/1587051422935"
webtalk_add_data -client sdk -key bspid -value "1586450648187" -context "sdk\\\\application/1587051422935"
webtalk_add_data -client sdk -key newbsp -value "false" -context "sdk\\\\application/1587051422935"
webtalk_add_data -client sdk -key os -value "freertos10_xilinx" -context "sdk\\\\application/1587051422935"
webtalk_add_data -client sdk -key apptemplate -value "freertos_lwip_echo_server" -context "sdk\\\\application/1587051422935"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1587051422935"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1587051422935"
webtalk_add_data -client sdk -key Procused -value "ps7_cortexa9" -context "sdk\\\\application/1587051422935"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1587305526623"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1587305526623"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1587305526623"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1587305526623"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1587305526623"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1587305526623"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1587305526623"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1587305526623"
webtalk_transmit -clientid 649696661 -regid "" -xml D:\\UTK_Project\\Daimler_Project\\XCP\\XCP.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html D:\\UTK_Project\\Daimler_Project\\XCP\\XCP.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm D:\\UTK_Project\\Daimler_Project\\XCP\\XCP.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
